{"levelname": "INFO", "asctime": "2023-10-17 23:02:35,169", "filename": "autoreload.py", "lineno": 668, "message": "Watching for file changes with StatReloader"}
{"levelname": "WARNING", "asctime": "2023-10-17 23:02:45,133", "filename": "log.py", "lineno": 241, "message": "Not Found: /", "status_code": 404, "request": "<WSGIRequest: GET '/'>"}
{"levelname": "WARNING", "asctime": "2023-10-17 23:02:45,839", "filename": "log.py", "lineno": 241, "message": "Not Found: /", "status_code": 404, "request": "<WSGIRequest: GET '/'>"}
{"levelname": "WARNING", "asctime": "2023-10-17 23:02:47,675", "filename": "log.py", "lineno": 241, "message": "Not Found: /favicon.ico", "status_code": 404, "request": "<WSGIRequest: GET '/favicon.ico'>"}
{"levelname": "INFO", "asctime": "2023-10-17 23:05:52,361", "filename": "autoreload.py", "lineno": 668, "message": "Watching for file changes with StatReloader"}
{"levelname": "WARNING", "asctime": "2023-10-17 23:05:55,159", "filename": "log.py", "lineno": 241, "message": "Not Found: /", "status_code": 404, "request": "<WSGIRequest: GET '/'>"}
{"levelname": "ERROR", "asctime": "2023-10-17 23:05:58,772", "filename": "log.py", "lineno": 241, "message": "Internal Server Error: /admin/", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\base.py\", line 187, in _get_session\n    return self._session_cache\n           ^^^^^^^^^^^^^^^^^^^\nAttributeError: 'SessionStore' object has no attribute '_session_cache'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\admin\\sites.py\", line 261, in wrapper\n    return self.admin_view(view, cacheable)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\decorators.py\", line 134, in _wrapper_view\n    response = view_func(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\views\\decorators\\cache.py\", line 62, in _wrapper_view_func\n    response = view_func(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\admin\\sites.py\", line 230, in inner\n    if not self.has_permission(request):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\admin\\sites.py\", line 203, in has_permission\n    return request.user.is_active and request.user.is_staff\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\functional.py\", line 266, in inner\n    self._setup()\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\functional.py\", line 419, in _setup\n    self._wrapped = self._setupfunc()\n                    ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\auth\\middleware.py\", line 25, in <lambda>\n    request.user = SimpleLazyObject(lambda: get_user(request))\n                                            ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\auth\\middleware.py\", line 11, in get_user\n    request._cached_user = auth.get_user(request)\n                           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\auth\\__init__.py\", line 191, in get_user\n    user_id = _get_user_session_key(request)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\auth\\__init__.py\", line 60, in _get_user_session_key\n    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])\n                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\base.py\", line 53, in __getitem__\n    return self._session[key]\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\base.py\", line 192, in _get_session\n    self._session_cache = self.load()\n                          ^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\db.py\", line 42, in load\n    s = self._get_session_from_db()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\db.py\", line 32, in _get_session_from_db\n    return self.model.objects.get(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\query.py\", line 633, in get\n    num = len(clone)\n          ^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\query.py\", line 380, in __len__\n    self._fetch_all()\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1881, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\sql\\compiler.py\", line 1560, in execute_sql\n    cursor = self.connection.cursor()\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\base\\base.py\", line 330, in cursor\n    return self._cursor()\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\base\\base.py\", line 306, in _cursor\n    self.ensure_connection()\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\base\\base.py\", line 289, in ensure_connection\n    self.connect()\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\base\\base.py\", line 269, in connect\n    conn_params = self.get_connection_params()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\postgresql\\base.py\", line 196, in get_connection_params\n    raise ImproperlyConfigured(\ndjango.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME or OPTIONS['service'] value.", "status_code": 500, "request": "<WSGIRequest: GET '/admin/'>"}
{"levelname": "ERROR", "asctime": "2023-10-17 23:05:59,244", "filename": "log.py", "lineno": 241, "message": "Internal Server Error: /admin/", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\base.py\", line 187, in _get_session\n    return self._session_cache\n           ^^^^^^^^^^^^^^^^^^^\nAttributeError: 'SessionStore' object has no attribute '_session_cache'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\admin\\sites.py\", line 261, in wrapper\n    return self.admin_view(view, cacheable)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\decorators.py\", line 134, in _wrapper_view\n    response = view_func(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\views\\decorators\\cache.py\", line 62, in _wrapper_view_func\n    response = view_func(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\admin\\sites.py\", line 230, in inner\n    if not self.has_permission(request):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\admin\\sites.py\", line 203, in has_permission\n    return request.user.is_active and request.user.is_staff\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\functional.py\", line 266, in inner\n    self._setup()\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\functional.py\", line 419, in _setup\n    self._wrapped = self._setupfunc()\n                    ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\auth\\middleware.py\", line 25, in <lambda>\n    request.user = SimpleLazyObject(lambda: get_user(request))\n                                            ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\auth\\middleware.py\", line 11, in get_user\n    request._cached_user = auth.get_user(request)\n                           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\auth\\__init__.py\", line 191, in get_user\n    user_id = _get_user_session_key(request)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\auth\\__init__.py\", line 60, in _get_user_session_key\n    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])\n                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\base.py\", line 53, in __getitem__\n    return self._session[key]\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\base.py\", line 192, in _get_session\n    self._session_cache = self.load()\n                          ^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\db.py\", line 42, in load\n    s = self._get_session_from_db()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\contrib\\sessions\\backends\\db.py\", line 32, in _get_session_from_db\n    return self.model.objects.get(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\query.py\", line 633, in get\n    num = len(clone)\n          ^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\query.py\", line 380, in __len__\n    self._fetch_all()\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1881, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\models\\sql\\compiler.py\", line 1560, in execute_sql\n    cursor = self.connection.cursor()\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\base\\base.py\", line 330, in cursor\n    return self._cursor()\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\base\\base.py\", line 306, in _cursor\n    self.ensure_connection()\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\base\\base.py\", line 289, in ensure_connection\n    self.connect()\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\utils\\asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\base\\base.py\", line 269, in connect\n    conn_params = self.get_connection_params()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\django-test-Ux_Ik7xH-py3.11\\Lib\\site-packages\\django\\db\\backends\\postgresql\\base.py\", line 196, in get_connection_params\n    raise ImproperlyConfigured(\ndjango.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME or OPTIONS['service'] value.", "status_code": 500, "request": "<WSGIRequest: GET '/admin/'>"}
